spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance?currentSchema=finance
    username: finance_adm
    password: finance_adm1234
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  kafka:
#    bootstrap-server: localhost:9092
#    producer:
#      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#    consumer:
#      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
