server:
  port: 9090

spring:
  main:
    banner-mode: off
  application:
    name: finance
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5432/finance?currentSchema=finance
      username: finance_adm
      password: finance_adm1234
      driver-class-name: org.postgresql.Driver
      database-platform: org.hibernate.dialect.Oracle12cDialect
      hikari:
        minimum-idle: 10
        maximum-pool-size: 20
    oracle:
      url: jdbc:oracle:thin:@//localhost:1521/pdbfinance
      username: finance_adm
      password: finance_adm1234
      driver-class-name: oracle.jdbc.OracleDriver
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hikari:
        minimum-idle: 10
        maximum-pool-size: 20
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-server: localhost:9092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} app=${spring.application.name} tid=[%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] -%5p ${PID:- } --- [%15.15thread] %-40.40logger{39} : M=%M, %m%n"
